import type { Article } from "./articles";

export const articlesFr: Article[] = [
  {
    slug: "saas-concept-to-production",
    title: "Construire un SaaS d'Entreprise, du Concept \u00e0 la Production",
    category: "Ing\u00e9nierie SaaS",
    summary: "Ce qui s\u00e9pare vraiment une d\u00e9mo qui fonctionne d'un produit SaaS sur lequel une entreprise peut faire reposer sa comptabilit\u00e9.",
    readingTime: 7,
    poster: "/images/articles/saas-concept-to-production.webp",
    blocks: [
      { type: "lead", text: "L'\u00e9cart entre une d\u00e9mo SaaS et un produit SaaS dont une entreprise d\u00e9pend r\u00e9ellement est presque totalement invisible sur une capture d'\u00e9cran \u2014 et constitue presque tout le travail." },
      { type: "h2", text: "Le mod\u00e8le de donn\u00e9es avant l'interface" },
      { type: "p", text: "Chaque projet SaaS d'entreprise commence par la m\u00eame tentation\u00a0: concevoir les \u00e9crans en premier, car c'est ce sur quoi les parties prenantes peuvent r\u00e9agir. L'ordre le plus durable est l'inverse. Le mod\u00e8le de donn\u00e9es \u2014 comment les entreprises, utilisateurs, permissions et enregistrements se relient \u2014 est la partie r\u00e9ellement co\u00fbteuse \u00e0 changer une fois de vraies donn\u00e9es en place." },
      { type: "h2", text: "Le multi-tenant est une d\u00e9cision, pas un d\u00e9tail" },
      { type: "p", text: "Qu'une plateforme serve une seule entreprise ou plusieurs change le sch\u00e9ma de base de donn\u00e9es, le flux d'authentification et le mod\u00e8le de facturation d\u00e8s le premier jour. Ajouter le multi-tenant apr\u00e8s une construction mono-tenant est l'une des migrations les plus co\u00fbteuses en logiciel \u2014 bien plus co\u00fbteuse que la planification suppl\u00e9mentaire n\u00e9cessaire pour bien d\u00e9cider d\u00e8s le d\u00e9part." },
      { type: "list", items: [
        "Mod\u00e9liser les entit\u00e9s centrales (entreprise, utilisateur, enregistrement) avant de concevoir le moindre \u00e9cran.",
        "D\u00e9cider t\u00f4t de la s\u00e9curit\u00e9 au niveau des lignes et des limites d'acc\u00e8s \u2014 elles touchent chaque requ\u00eate ensuite.",
        "Traiter la facturation et la logique des forfaits comme une infrastructure centrale, pas une fonctionnalit\u00e9 \u00e0 ajouter plus tard.",
      ] },
      { type: "callout", variant: "tip", title: "Le test de concurrence", text: "Avant de livrer un workflow financier ou transactionnel, demandez ce qui se passe si deux utilisateurs effectuent la m\u00eame action au m\u00eame instant. Si la r\u00e9ponse honn\u00eate est \u00abje ne suis pas s\u00fbr\u00bb, c'est la prochaine chose \u00e0 corriger, pas \u00e0 lancer." },
      { type: "h2", text: "La production est une barre diff\u00e9rente de \u00abfonctionne\u00bb" },
      { type: "p", text: "Une fonctionnalit\u00e9 qui fonctionne en d\u00e9mo et une fonctionnalit\u00e9 qui survit en production sont deux affirmations diff\u00e9rentes. La production signifie g\u00e9rer un paiement qui \u00e9choue \u00e0 mi-chemin, un formulaire soumis deux fois, un rapport demand\u00e9 sans donn\u00e9es encore disponibles. Rien de tout cela n'appara\u00eet dans une pr\u00e9sentation, et tout cela d\u00e9termine si une entreprise peut r\u00e9ellement fonctionner sur le logiciel." },
      { type: "h2", text: "\u00c0 retenir" },
      { type: "p", text: "Le SaaS d'entreprise se gagne dans les parties que personne ne photographie \u2014 le mod\u00e8le de donn\u00e9es, les limites du multi-tenant, le comportement en cas d'\u00e9chec concurrent ou partiel. Bien r\u00e9ussir les 20\u00a0% visibles est n\u00e9cessaire mais pas suffisant\u00a0; ce sont les 80\u00a0% restants qui font la diff\u00e9rence avec un niveau entreprise." },
    ],
  },
  {
    slug: "accounting-erp-platforms",
    title: "Concevoir des Plateformes Comptables et ERP pour de Vraies Entreprises",
    category: "SaaS d'Entreprise",
    summary: "Un logiciel de comptabilit\u00e9 n'est pas une liste de fonctionnalit\u00e9s \u2014 c'est un syst\u00e8me de confiance. Voici ce que cela change dans sa conception.",
    readingTime: 6,
    poster: "/images/articles/accounting-erp-platforms.webp",
    blocks: [
      { type: "lead", text: "Un bug dans la plupart des logiciels produit un utilisateur perplexe. Un bug dans un logiciel de comptabilit\u00e9 produit un chiffre erron\u00e9 sur une d\u00e9claration fiscale. Cette diff\u00e9rence devrait guider presque chaque d\u00e9cision de conception." },
      { type: "h2", text: "Chaque chiffre a besoin d'une piste d'audit" },
      { type: "p", text: "Dans un syst\u00e8me comptable, aucun total ne devrait exister sans un chemin tra\u00e7able vers les transactions qui l'ont produit. Ce n'est pas une fonctionnalit\u00e9 de reporting \u2014 c'est une exigence structurelle \u00e0 int\u00e9grer d\u00e8s la premi\u00e8re migration du mod\u00e8le de donn\u00e9es, pas \u00e0 ajouter plus tard quand un audit le demande." },
      { type: "h2", text: "Notes de cr\u00e9dit et paiements ne sont pas de simples CRUD" },
      { type: "p", text: "Appliquer une note de cr\u00e9dit, enregistrer un paiement partiel ou annuler une \u00e9criture touchent tous plusieurs enregistrements qui doivent rester coh\u00e9rents m\u00eame en usage concurrent. Ces workflows m\u00e9ritent des fonctions de base de donn\u00e9es transactionnelles avec un verrouillage appropri\u00e9, pas une logique c\u00f4t\u00e9 client qui suppose que rien d'autre ne se passe en m\u00eame temps." },
      { type: "table", headers: ["Workflow", "Approche na\u00efve", "Ce qui tient la route"], rows: [
        ["Enregistrement de paiement", "Mise \u00e0 jour du solde directement depuis le client", "Transaction c\u00f4t\u00e9 serveur avec verrouillage de lignes"],
        ["Application de note de cr\u00e9dit", "Ajustement manuel du solde", "Fonction atomique liant le cr\u00e9dit \u00e0 des factures pr\u00e9cises"],
        ["Reporting multi-soci\u00e9t\u00e9s", "Requ\u00eates s\u00e9par\u00e9es fusionn\u00e9es c\u00f4t\u00e9 interface", "Requ\u00eates par soci\u00e9t\u00e9 avec logique d'agr\u00e9gation partag\u00e9e"],
      ] },
      { type: "callout", variant: "warning", title: "Le pi\u00e8ge de la r\u00e9conciliation", text: "Si un syst\u00e8me permet au solde affich\u00e9 et \u00e0 la somme des transactions sous-jacentes de diverger un jour, cela arrivera \u2014 g\u00e9n\u00e9ralement d\u00e9couvert par un client, pas par des tests." },
      { type: "h2", text: "\u00c0 retenir" },
      { type: "p", text: "Un logiciel de comptabilit\u00e9 est jug\u00e9 sur la confiance qu'on peut accorder aux chiffres sous pression \u2014 usage concurrent, \u00e9checs partiels, audits des ann\u00e9es plus tard. Construire pour cette exigence d\u00e8s le d\u00e9but co\u00fbte plus cher au d\u00e9part et bien moins cher sur la dur\u00e9e de vie du produit." },
    ],
  },
  {
    slug: "product-engineering-beyond-code",
    title: "L'Ing\u00e9nierie Produit au-del\u00e0 de l'\u00c9criture de Code",
    category: "Pens\u00e9e Produit",
    summary: "Les aspects de la livraison d'un produit qui n'ont rien \u00e0 voir avec la syntaxe \u2014 et pourquoi ils comptent g\u00e9n\u00e9ralement davantage.",
    readingTime: 6,
    poster: "/images/articles/product-engineering-beyond-code.webp",
    blocks: [
      { type: "lead", text: "\u00c9crire du code qui fonctionne repr\u00e9sente les 60\u00a0% faciles de la livraison d'un produit. Les 40\u00a0% restants \u2014 d\u00e9cider quoi construire, pour qui, et si cela a r\u00e9ellement r\u00e9solu quelque chose \u2014 d\u00e9terminent souvent la r\u00e9ussite ou l'\u00e9chec d'un projet." },
      { type: "h2", text: "Cadrer est une comp\u00e9tence, pas une formalit\u00e9" },
      { type: "p", text: "La diff\u00e9rence entre une version un utile et une version un surcharg\u00e9e se r\u00e9sume g\u00e9n\u00e9ralement \u00e0 une seule question pos\u00e9e t\u00f4t et honn\u00eatement\u00a0: quelle est la plus petite chose qui aiderait r\u00e9ellement une personne pr\u00e9cise, aujourd'hui\u00a0? Tout le reste peut attendre." },
      { type: "h2", text: "Parler aux futurs utilisateurs vaut mieux que deviner" },
      { type: "p", text: "L'exp\u00e9rience en op\u00e9rations l'enseigne directement \u2014 un responsable d'entrep\u00f4t peut dire en cinq minutes ce qu'un tableau de bord de reporting doit afficher, bien plus vite et plus pr\u00e9cis\u00e9ment qu'en it\u00e9rant \u00e0 l'aveugle sur trois rounds de design." },
      { type: "list", items: [
        "D\u00e9finir ce que \u00abterminé\u00bb signifie pour la version un avant d'\u00e9crire une ligne de code, en une phrase v\u00e9rifiable par un non-technicien.",
        "Livrer la version la plus \u00e9troite qui soit r\u00e9ellement utilisable, pas la plus compl\u00e8te.",
        "Consid\u00e9rer la premi\u00e8re semaine d'usage r\u00e9el comme plus instructive qu'un mois de revue interne.",
      ] },
      { type: "callout", variant: "info", text: "L'\u00e9chec produit le plus courant n'est pas un mauvais code \u2014 c'est une r\u00e9ponse bien construite \u00e0 la mauvaise question, d\u00e9couverte seulement apr\u00e8s le lancement." },
      { type: "h2", text: "\u00c0 retenir" },
      { type: "p", text: "L'ing\u00e9nierie produit est la discipline qui s'assure que le code \u00e9crit m\u00e9rite de l'\u00eatre. Ce jugement n'appara\u00eet pas dans un diff, mais il fait g\u00e9n\u00e9ralement la diff\u00e9rence entre un projet qui sort et un projet dont les gens se servent r\u00e9ellement." },
    ],
  },
  {
    slug: "rbac-with-supabase",
    title: "Construire un Contr\u00f4le d'Acc\u00e8s S\u00e9curis\u00e9 par R\u00f4les avec Supabase",
    category: "Architecture Backend",
    summary: "Une approche concr\u00e8te du contr\u00f4le d'acc\u00e8s par r\u00f4les qui tient face \u00e0 un vrai audit, pas seulement \u00e0 une d\u00e9mo de connexion.",
    readingTime: 7,
    poster: "/images/articles/rbac-with-supabase.webp",
    blocks: [
      { type: "lead", text: "Le contr\u00f4le d'acc\u00e8s par r\u00f4les est facile \u00e0 simuler et r\u00e9ellement difficile \u00e0 bien faire. La diff\u00e9rence appara\u00eet la premi\u00e8re fois que quelqu'un essaie d'acc\u00e9der \u00e0 quelque chose qu'il ne devrait pas \u2014 et soit ne peut pas, soit peut." },
      { type: "h2", text: "La s\u00e9curit\u00e9 au niveau des lignes appartient \u00e0 la base de donn\u00e9es, pas seulement \u00e0 l'interface" },
      { type: "p", text: "Cacher un bouton pour les utilisateurs non autoris\u00e9s est une d\u00e9cision UX, pas une limite de s\u00e9curit\u00e9. Le vrai contr\u00f4le d'acc\u00e8s doit \u00eatre appliqu\u00e9 au niveau de la base de donn\u00e9es \u2014 les politiques de s\u00e9curit\u00e9 au niveau des lignes de Supabase font qu'un appel API direct ne peut pas contourner ce qu'un bouton cach\u00e9 fait simplement d\u00e9courager." },
      { type: "h2", text: "Les r\u00f4les doivent refl\u00e9ter de vrais m\u00e9tiers, pas des niveaux g\u00e9n\u00e9riques" },
      { type: "p", text: "\u00abAdmin, \u00e9diteur, lecteur\u00bb est un choix par d\u00e9faut pratique, mais il correspond rarement \u00e0 la fa\u00e7on dont une vraie entreprise r\u00e9partit les responsabilit\u00e9s. Le personnel finance, commercial et entrep\u00f4t a besoin de tranches de donn\u00e9es diff\u00e9rentes et pr\u00e9cises \u2014 les mod\u00e9liser pr\u00e9cis\u00e9ment d\u00e8s le d\u00e9part \u00e9vite une refonte douloureuse des permissions plus tard." },
      { type: "list", items: [
        "\u00c9crire les politiques RLS comme source de v\u00e9rit\u00e9\u00a0; les restrictions d'interface sont une couche de confort, pas la limite elle-m\u00eame.",
        "Tester le contr\u00f4le d'acc\u00e8s du point de vue d'un compte non autoris\u00e9, pas seulement autoris\u00e9.",
        "Journaliser les refus de permission \u2014 c'est souvent le premier signe d'une politique erron\u00e9e, pas juste d'un utilisateur inhabituel.",
      ] },
      { type: "callout", variant: "tip", title: "La question de l'audit", text: "Avant le lancement, demandez\u00a0: si je donnais \u00e0 un auditeur un acc\u00e8s direct \u00e0 la base de donn\u00e9es, pourrait-il voir qui peut voir quoi, et pourquoi\u00a0? Si la r\u00e9ponse n\u00e9cessite de lire le code applicatif, le mod\u00e8le d'acc\u00e8s a besoin d'une refonte." },
      { type: "h2", text: "\u00c0 retenir" },
      { type: "p", text: "Un vrai contr\u00f4le d'acc\u00e8s par r\u00f4les vit dans la couche d'application de la base de donn\u00e9es, mod\u00e9lis\u00e9 sur la fa\u00e7on dont l'entreprise r\u00e9partit r\u00e9ellement le travail \u2014 pas dans un ensemble de boutons cach\u00e9s qui correspondent par hasard \u00e0 un sc\u00e9nario de d\u00e9mo." },
    ],
  },
  {
    slug: "marketplace-platforms-that-scale",
    title: "Concevoir des Plateformes Marketplace qui Passent \u00e0 l'\u00c9chelle",
    category: "Ing\u00e9nierie Marketplace",
    summary: "Pourquoi les marketplaces r\u00e9ussissent ou \u00e9chouent d'abord c\u00f4t\u00e9 vendeur, et ce que cela implique pour leur construction.",
    readingTime: 6,
    poster: "/images/articles/marketplace-platforms-that-scale.webp",
    blocks: [
      { type: "lead", text: "Chaque marketplace a deux audiences, et presque chaque marketplace qui \u00e9choue s'est d'abord concentr\u00e9e sur la mauvaise." },
      { type: "h2", text: "Les vendeurs arrivent avant les acheteurs, ou personne n'arrive" },
      { type: "p", text: "Une marketplace sans annonces n'a rien \u00e0 offrir \u00e0 un acheteur. Cela signifie que le parcours d'int\u00e9gration vendeur \u2014 la facilit\u00e9 \u00e0 publier une annonce, \u00eatre pay\u00e9, et faire confiance \u00e0 la plateforme \u2014 doit \u00eatre r\u00e9solu avant que le polish c\u00f4t\u00e9 acheteur ne m\u00e9rite un investissement." },
      { type: "h2", text: "Les signaux de confiance comptent plus que le nombre de fonctionnalit\u00e9s" },
      { type: "p", text: "Les acheteurs sur une nouvelle marketplace prennent un risque plus grand que sur une marketplace \u00e9tablie. Avis, vendeurs v\u00e9rifi\u00e9s, processus de litige clairs et d\u00e9lais de r\u00e9ponse visibles font plus pour la conversion qu'une option de filtre suppl\u00e9mentaire ou une recherche plus sophistiqu\u00e9e." },
      { type: "list", items: [
        "Concevoir le parcours de publication vendeur pour qu'il prenne des minutes, pas un apr\u00e8s-midi.",
        "Rendre les signaux de confiance (avis, v\u00e9rification, d\u00e9lai de r\u00e9ponse) visibles avant le clic, pas apr\u00e8s.",
        "Commencer par une seule cat\u00e9gorie \u00e9troite bien faite plut\u00f4t que toutes les cat\u00e9gories faites superficiellement.",
      ] },
      { type: "callout", variant: "info", text: "Une marketplace avec 50 excellentes annonces dans une cat\u00e9gorie convertit g\u00e9n\u00e9ralement mieux qu'une avec 500 annonces m\u00e9diocres r\u00e9parties sur dix." },
      { type: "h2", text: "\u00c0 retenir" },
      { type: "p", text: "Les plateformes marketplace passent \u00e0 l'\u00e9chelle en partant d'un probl\u00e8me c\u00f4t\u00e9 vendeur r\u00e9solu \u2014 obtenir des vendeurs qui publient avec confiance dans une cat\u00e9gorie, puis \u00e9largir. Construire pour les deux c\u00f4t\u00e9s \u00e9galement d\u00e8s le premier jour signifie souvent qu'aucun des deux n'obtient ce dont il a r\u00e9ellement besoin en premier." },
    ],
  },
  {
    slug: "nextjs-performance-seo",
    title: "Bonnes Pratiques de Performance et SEO avec Next.js",
    category: "Performance Web",
    summary: "Les fondamentaux Next.js qui font r\u00e9ellement la diff\u00e9rence sur la vitesse et la visibilit\u00e9 \u2014 pas les raccourcis \u00e0 la mode.",
    readingTime: 6,
    poster: "/images/articles/nextjs-performance-seo.webp",
    blocks: [
      { type: "lead", text: "La plupart des conseils de performance Next.js en ligne courent apr\u00e8s des gains marginaux. Une courte liste de fondamentaux explique l'essentiel de la vraie diff\u00e9rence entre un site rapide et un site lent." },
      { type: "h2", text: "La g\u00e9n\u00e9ration statique reste l'option la plus rapide disponible" },
      { type: "p", text: "Toute page qui n'a pas besoin de personnalisation par requ\u00eate devrait \u00eatre g\u00e9n\u00e9r\u00e9e statiquement au build. C'est le plus grand levier de performance du framework, et il est souvent n\u00e9glig\u00e9 simplement parce que le rendu dynamique est le chemin de moindre r\u00e9sistance." },
      { type: "h2", text: "Les images sont g\u00e9n\u00e9ralement le vrai goulot d'\u00e9tranglement" },
      { type: "p", text: "L'optimisation d'image int\u00e9gr\u00e9e de Next.js g\u00e8re automatiquement le dimensionnement responsive et les formats modernes \u2014 l'erreur consiste g\u00e9n\u00e9ralement \u00e0 ne pas l'utiliser partout, ou \u00e0 servir une image de 2000px \u00e0 un composant affich\u00e9 \u00e0 400px de large." },
      { type: "table", headers: ["Levier", "Effort", "Impact typique"], rows: [
        ["G\u00e9n\u00e9ration statique plut\u00f4t que rendu dynamique", "Faible", "\u00c9lev\u00e9"],
        ["next/image partout, jamais de <img> brut", "Faible", "\u00c9lev\u00e9"],
        ["M\u00e9tadonn\u00e9es et donn\u00e9es structur\u00e9es par page", "Moyen", "\u00c9lev\u00e9 pour le SEO sp\u00e9cifiquement"],
        ["D\u00e9coupage du bundle pour les composants rarement utilis\u00e9s", "Moyen", "Mod\u00e9r\u00e9"],
      ] },
      { type: "callout", variant: "tip", title: "La v\u00e9rification des m\u00e9tadonn\u00e9es", text: "Chaque page devrait avoir un titre et une description uniques qui pourraient tenir seuls dans un r\u00e9sultat de recherche \u2014 si deux pages d'un site partagent les m\u00eames m\u00e9tadonn\u00e9es, c'est une lacune SEO concr\u00e8te et corrigeable." },
      { type: "h2", text: "\u00c0 retenir" },
      { type: "p", text: "La performance et le SEO sous Next.js r\u00e9compensent surtout l'application coh\u00e9rente des fondamentaux sur chaque page, plut\u00f4t que la poursuite d'une optimisation exotique sur une page pendant que les m\u00e9tadonn\u00e9es et la gestion des images restent incoh\u00e9rentes partout ailleurs." },
    ],
  },
  {
    slug: "business-operations-to-software",
    title: "Appliquer l'Exp\u00e9rience en Op\u00e9rations d'Entreprise \u00e0 la Conception Logicielle",
    category: "Pens\u00e9e Produit",
    summary: "Ce que des ann\u00e9es sur le terrain op\u00e9rationnel enseignent sur la construction de logiciels qui survivent \u00e0 un usage r\u00e9el.",
    readingTime: 6,
    poster: "/images/articles/business-operations-to-software.webp",
    blocks: [
      { type: "lead", text: "Un logiciel construit par quelqu'un qui n'a jamais fait que du logiciel a tendance \u00e0 optimiser pour la d\u00e9mo. Un logiciel inform\u00e9 par une vraie exp\u00e9rience op\u00e9rationnelle a tendance \u00e0 optimiser pour le pire jour." },
      { type: "h2", text: "Les op\u00e9rations \u00e9chouent bruyamment\u00a0; le logiciel \u00e9choue en douceur" },
      { type: "p", text: "Un bug dans une application web typique signifie un utilisateur perplexe et un ticket de support. Une panne dans un syst\u00e8me logistique ou d'entrep\u00f4t signifie un camion \u00e0 l'arr\u00eat ou une exp\u00e9dition manqu\u00e9e \u2014 un ordre de cons\u00e9quence tr\u00e8s diff\u00e9rent qui change la fa\u00e7on dont les cas d'exception sont con\u00e7us." },
      { type: "h2", text: "Le reporting existe pour r\u00e9pondre \u00e0 une question, pas pour para\u00eetre complet" },
      { type: "p", text: "Le reporting op\u00e9rationnel a un seul travail\u00a0: dire \u00e0 quelqu'un quoi faire ensuite. Un tableau de bord avec quarante indicateurs et aucune action claire est op\u00e9rationnellement inutile quelle que soit sa finition \u2014 une le\u00e7on qui s'applique directement aux panneaux d'administration et tableaux de bord d'entreprise en logiciel." },
      { type: "list", items: [
        "Concevoir d'abord pour le cas d'exception \u2014 le chemin id\u00e9al repr\u00e9sente g\u00e9n\u00e9ralement les 20\u00a0% faciles.",
        "Juger un rapport par la d\u00e9cision qu'il permet, pas par les donn\u00e9es qu'il affiche.",
        "Consid\u00e9rer un processus qui d\u00e9pend de la m\u00e9moire d'une seule personne comme un bug, pas comme une solution de contournement.",
      ] },
      { type: "callout", variant: "info", text: "Avant de livrer un syst\u00e8me, demandez \u00e0 quoi il ressemble un jour difficile \u2014 forte charge, une int\u00e9gration cl\u00e9 en panne, un utilisateur faisant quelque chose d'inattendu \u2014 pas seulement \u00e0 quoi il ressemble dans une d\u00e9mo propre." },
      { type: "h2", text: "\u00c0 retenir" },
      { type: "p", text: "Des ann\u00e9es pass\u00e9es responsable de ce qui se passe quand un vrai syst\u00e8me \u00e9choue forgent un instinct difficile \u00e0 apprendre d'un tutoriel\u00a0: concevoir pour l'exception, et juger le logiciel sur sa capacit\u00e9 \u00e0 tenir sous pression, pas sur son apparence dans une d\u00e9monstration." },
    ],
  },
  {
    slug: "bilingual-digital-products-europe",
    title: "Construire des Produits Digitaux Bilingues pour les March\u00e9s Europ\u00e9ens",
    category: "Internationalisation",
    summary: "Ce qui change r\u00e9ellement quand un produit doit fonctionner \u00e9galement bien dans deux langues \u2014 et ce que la traduction m\u00e9canique manque.",
    readingTime: 6,
    poster: "/images/articles/bilingual-digital-products-europe.webp",
    blocks: [
      { type: "lead", text: "Un produit bilingue n'est pas un produit monolingue avec une copie traduite de chaque texte. Trait\u00e9 ainsi, cela se voit g\u00e9n\u00e9ralement dans les d\u00e9tails \u2014 le SEO, le ton, m\u00eame le routage." },
      { type: "h2", text: "Le routage et le SEO ont besoin d'une vraie strat\u00e9gie, pas d'un ajout tardif" },
      { type: "p", text: "Du contenu dupliqu\u00e9 entre langues sans balisage hreflang correct nuit activement \u00e0 la visibilit\u00e9 dans les moteurs de recherche au lieu de l'aider. Chaque page a besoin d'une URL canonique claire, de liens de langue alternative corrects, et de m\u00e9tadonn\u00e9es sp\u00e9cifiques \u00e0 la langue \u2014 pas simplement d'un texte traduit sous les m\u00eames balises que l'original." },
      { type: "h2", text: "La traduction m\u00e9canique se lit comme une traduction m\u00e9canique" },
      { type: "p", text: "Les recruteurs et clients des march\u00e9s francophones remarquent le ton autant que l'exactitude. Une traduction litt\u00e9rale d'une structure de phrase anglaise se lit souvent de fa\u00e7on raide en fran\u00e7ais, m\u00eame quand chaque mot est techniquement correct \u2014 le fran\u00e7ais professionnel a besoin de son propre rythme de phrase, pas d'un miroir mot \u00e0 mot." },
      { type: "list", items: [
        "Garder les noms de technologies et de marques non traduits \u2014 traduire \u00abReact\u00bb ou \u00abNext.js\u00bb n'aide personne.",
        "\u00c9crire le texte marketing de chaque langue avec sa propre voix, pas comme une passe de traduction sur l'autre.",
        "Tester le s\u00e9lecteur de langue sur chaque type de page, y compris les pages dynamiques \u2014 c'est la premi\u00e8re chose qu'un visiteur bilingue essaie.",
      ] },
      { type: "callout", variant: "tip", title: "Le test de lecture \u00e0 voix haute", text: "Si une phrase fran\u00e7aise sonne \u00e9trangement lue \u00e0 voix haute par un francophone, c'est probablement une traduction litt\u00e9rale plut\u00f4t qu'une r\u00e9\u00e9criture native \u2014 \u00e0 corriger m\u00eame si un outil de traduction la jugerait \u00abcorrecte\u00bb." },
      { type: "h2", text: "\u00c0 retenir" },
      { type: "p", text: "Un produit r\u00e9ellement bilingue traite chaque langue comme une version \u00e0 part enti\u00e8re du site, pas comme une couche traduite sur une version canonique unique \u2014 cela se voit dans le routage, le SEO, et simplement dans le naturel du texte pour un lecteur natif." },
    ],
  },
];
